name: Quality pipe 
 
on: 
 pull_request: 
  types: [opened, synchronize] 
  branches: 
  - main
  - formal
  - proto
 
jobs: 
 lint: 
  runs-on: ubuntu-latest 
  steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 
      with: 
        ref: ${{ github.event.pull_request.head.sha }} 

    - name: Lint     
      uses: dalance/svlint-action@master
      with:
        files: |
          rtl/*.sv
      env:
        SVLINT_CONFIG: .svlint.toml